import mysql from 'mysql2/promise';
import { Tenant } from '../types/auth.types';
import { DatabaseTransaction, Queryable } from '../../../database/database.types';

export class TenantRepository {
  constructor(private readonly executor: Queryable) {}

  /**
   * Insert a new tenant record
   * Uses UUIDs generated by the service
   */
  async create(
    id: string,
    name: string,
    executor: Queryable | DatabaseTransaction = this.executor
  ): Promise<void> {
    const sql = `
      INSERT INTO tenants (id, name, created_at, updated_at) 
      VALUES (?, ?, NOW(), NOW())
    `;
    await executor.execute<mysql.ResultSetHeader>(sql, [id, name]);
  }

  /**
   * Find tenant by ID
   */
  async findById(id: string): Promise<Tenant | null> {
    const sql = `SELECT * FROM tenants WHERE id = ? LIMIT 1`;
    const [rows] = await this.executor.execute<mysql.RowDataPacket[]>(sql, [id]);
    const results = rows as Tenant[];
    return results.length ? results[0] : null;
  }

  /**
   * Check if a globally unique company name already exists
   */
  async findByName(name: string): Promise<Tenant | null> {
    const sql = `SELECT * FROM tenants WHERE name = ? LIMIT 1`;
    const [rows] = await this.executor.execute<mysql.RowDataPacket[]>(sql, [name]);
    const results = rows as Tenant[];
    return results.length ? results[0] : null;
  }
}
