CREATE TABLE IF NOT EXISTS products (
  id CHAR(36) PRIMARY KEY,
  tenant_id CHAR(36) NOT NULL,
  unit_id CHAR(36) DEFAULT NULL,
  name VARCHAR(160) NOT NULL,
  slug VARCHAR(190) NOT NULL,
  description TEXT DEFAULT NULL,
  product_type ENUM('SIMPLE', 'VARIABLE', 'SERVICE', 'BUNDLE') NOT NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  sku VARCHAR(80) DEFAULT NULL,
  barcode VARCHAR(80) DEFAULT NULL,
  is_sellable BOOLEAN NOT NULL DEFAULT TRUE,
  is_purchasable BOOLEAN NOT NULL DEFAULT TRUE,
  track_inventory BOOLEAN NOT NULL DEFAULT TRUE,
  allow_returns BOOLEAN NOT NULL DEFAULT TRUE,
  allow_backorder BOOLEAN NOT NULL DEFAULT FALSE,
  min_stock_level DECIMAL(18, 4) DEFAULT NULL,
  max_stock_level DECIMAL(18, 4) DEFAULT NULL,
  cost_price DECIMAL(18, 4) DEFAULT NULL,
  selling_price DECIMAL(18, 4) DEFAULT NULL,
  currency_code CHAR(3) DEFAULT NULL,
  created_by CHAR(36) DEFAULT NULL,
  updated_by CHAR(36) DEFAULT NULL,
  deleted_by CHAR(36) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_products_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_products_unit
    FOREIGN KEY (unit_id) REFERENCES product_units(id) ON DELETE SET NULL,
  CONSTRAINT uq_products_tenant_slug UNIQUE (tenant_id, slug),
  CONSTRAINT uq_products_tenant_sku UNIQUE (tenant_id, sku),
  CONSTRAINT uq_products_tenant_barcode UNIQUE (tenant_id, barcode),
  INDEX idx_products_tenant_deleted (tenant_id, deleted_at),
  INDEX idx_products_tenant_status (tenant_id, status),
  INDEX idx_products_tenant_type (tenant_id, product_type),
  INDEX idx_products_tenant_name (tenant_id, name),
  INDEX idx_products_tenant_created (tenant_id, created_at),
  INDEX idx_products_tenant_deleted_updated_id (tenant_id, deleted_at, updated_at, id),
  INDEX idx_products_tenant_deleted_created_id (tenant_id, deleted_at, created_at, id),
  INDEX idx_products_tenant_deleted_name_id (tenant_id, deleted_at, name, id),
  INDEX idx_products_tenant_deleted_status_updated_id (tenant_id, deleted_at, status, updated_at, id),
  INDEX idx_products_tenant_deleted_type_updated_id (tenant_id, deleted_at, product_type, updated_at, id),
  INDEX idx_products_tenant_deleted_unit_updated_id (tenant_id, deleted_at, unit_id, updated_at, id),
  INDEX idx_products_tenant_sellable (tenant_id, is_sellable),
  INDEX idx_products_tenant_purchasable (tenant_id, is_purchasable)
);
